name: PR Subject
on: [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Validate
        uses: ./.github/actions/validate-commit-message

# 問題:
# - pull_request.synchronize 以外のアクションで呼ばれない。
# - re-run すると pull_request イベントじゃない。
