name: Test
on:
  push:
    branches: [test]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Push
        uses: mysticatea-actions/gh-pages@v0.0.0-alpha.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceDir: docs
